import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Authprovider from "@/Authorize/Authprovider/Authprovider";
import { Toaster } from "@/components/ui/sonner";

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Cleverank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito_sans.className} antialiased`}>
        <Toaster richColors />
        <Authprovider>{children}</Authprovider>
      </body>
    </html>
  );
}
