const Quotes = [
  "Reading research papers is like upgrading your brain to 'genius mode'—no Netflix binge can do that!",
  "Research papers put your procrastination abilities to the test—just when you thought you had them mastered.",
  "Reading a research paper is the ultimate mental workout—minus the gym clothes and sweat!",
  "Want real science? Research papers, not Google’s ‘Top 10 results’!",
  "Knowledge is power, but sometimes research papers also come with a built-in nap feature.",
  "If you're not diving into research papers, you're missing out on all the 'hidden gems' your professors never mentioned.",
  "Reading research papers is like deciphering ancient manuscripts—except the jargon is way less fun.",
  "Impress people at parties by casually mentioning ‘methodology’ and ‘abstracts’—research papers have got your back.",
  "Skimming the intro of a research paper is not the same as being prepared—trust me, I’ve tried.",
  "Research papers: the ultimate sleep-inducers, but at least your dreams are filled with citations.",
  "Research papers: harder to understand than your professor’s handwriting, and just as long.",
  "Reading a research paper is like starting a Netflix series, except the plot doesn’t make sense, and there's no happy ending.",
  "Googling won’t give you the academic street cred you need—research papers will.",
  "Why read a research paper? So you can pretend to understand the abstract during that next group discussion.",
  "Wikipedia might confuse you, but research papers take confusion to a whole new level.",
  "Research papers prove that the best way to learn is by being confused, then still getting an A.",
  "Want to sound smarter than you really are? Just sprinkle some research paper quotes in your conversation.",
  "Research papers teach you that ‘conclusion’ really means ‘more research is needed.’",
  "In research papers, ‘results’ just mean you have more questions than when you started.",
  "Research papers give you a power boost of knowledge, and a side effect of caffeine-fueled anxiety.",
  "Impress your professor by dropping words like ‘methodology’ and ‘data set’ in casual conversation.",
  "Reading research papers: it's like a treasure hunt—but the treasure is a headache you can’t escape.",
  "Guessing isn’t an academic strategy—unless you’re skipping research papers.",
  "Why read research papers? So you can finally stop Googling ‘What is a chi-square test?’",
  "Research papers let you sleep in public and still be productive—just pretend you’re pondering complex ideas.",
  "Every research paper will make you question your life choices, one citation at a time.",
  "The more research papers you read, the more you realize the authors are probably way smarter than you.",
  "Reading research papers is like playing Minesweeper: one wrong click, and your brain is a disaster.",
  "Research papers: it’s not about what you learn, it’s about surviving the long, tedious pages.",
  "Want to say ‘I didn’t know that’? Make sure you’ve got a citation to back it up!",
  "Reading research papers leaves you with more questions than answers—welcome to academia.",
  "Research papers show you exactly how much you don’t know—right after you've spent hours reading them.",
  "In academia, ‘winging it’ doesn't cut it—you need to read research papers to back up every claim.",
  "Research papers: like a strong cup of coffee—bitter, but keeps you awake and leaves you with a headache.",
  "References are your best friend in research papers, but the figures will make you question everything.",
  "Reading research papers is like running a marathon—slow, painful, but with that sweet sense of accomplishment at the end.",
  "Research papers are like a 1000-piece puzzle—except all the pieces look exactly the same.",
  "In research papers, ‘abstract’ is the opposite of simple—it’s just a taste of the confusion ahead.",
  "Why read research papers? Because your professor’s 'just Google it' answer won’t get you through the final exam.",
  "Research papers are for the brave—quick summaries are for those who want to stay comfortable.",
  "Reading research papers is like binge-watching a documentary—except the plot is a maze, and the credits never roll.",
  "Research papers: the only way to make Google feel like a beginner’s guide to real knowledge.",
  "Why read a research paper? Because you can't just ‘Google’ your way through an entire semester.",
  "Reading research papers: like exploring an intellectual jungle where the vines are footnotes and the wild animals are theories.",
  "Research papers: where ‘understanding’ is a goal, but ‘surviving the footnotes’ is the real achievement.",
  "Reading research papers: because ‘just Googling it’ only works for recipes, not for a degree.",
  "Want to sound impressive? Drop a research paper reference in the middle of any conversation and watch people nod in awe.",
  "Research papers: because ‘quick summaries’ are for the lazy, and ‘detailed analysis’ is for the bold.",
  "Reading research papers: where you start off with curiosity, then end up with existential dread and a citation list.",
  "Research papers: the secret ingredient to sounding smart without even knowing what you're talking about.",
  "Why read research papers? Because 'I read the first paragraph’ doesn’t quite cut it on exams.",
  "Research papers: where the introduction has you thinking you understand everything… then the methods leave you questioning life.",
  "Reading a research paper: because in academia, a 'gut feeling' isn’t considered solid evidence.",
  "Research papers: they make you feel like an expert in the field, until you try explaining it to your parents.",
  "Why read research papers? So you can understand what ‘statistical significance’ really means—then pretend to explain it at dinner.",
  "Research papers are the best way to realize that ‘reading’ is actually just decoding a bunch of big words.",
  "Research papers: like building a house—one footnote at a time, but somehow it still feels like a pile of bricks.",
  "Reading research papers: the fastest way to learn that no one has all the answers—except, maybe, the author… but even they have a bibliography.",
  "Research papers are like math problems: the more you look, the more you wonder if you’ll ever get the answer.",
  "Want to get ahead? Skip the memes and read research papers—they're full of hidden gems that Google can’t find.",
  "Reading research papers is like being a detective, but your only lead is a 50-page document of abstract terms.",
  "Research papers: when you finally understand a paragraph, but realize it’s still just a tiny piece of the puzzle.",
  "Reading research papers: because who needs a social life when you can have peer-reviewed articles?",
  "Why read research papers? Because citing Wikipedia in an exam isn’t the academic flex you think it is.",
  "Research papers: where your concentration is tested as much as your reading skills.",
  "Reading research papers: where the only thing more confusing than the jargon is why you’re still reading it.",
  "Research papers: teaching you how to use 50 words when 5 would do—because complexity is the key to academic success.",
  "Why read a research paper? Because 'I don’t know' isn’t a good enough answer when you’re asked about 'methodology.'",
  "Reading research papers: because sometimes the only thing more complicated than the subject is the formatting.",
  "Research papers: they’ll teach you everything you need to know, except how to pronounce half the terms in the references section.",
];

export default Quotes;
